"""Transition diagrams of the Stage 3 automata (Mermaid and Graphviz DOT).

The diagrams are generated from ``recognition.automaton_tuple``, i.e. from
the same pyformlang automata that classify résumés, so the documentation can
never drift away from the implementation. Regenerate them with::

    python scripts/export_diagrams.py

Conventions in every diagram:

* an arrow from an invisible point marks the initial state q0 / D0;
* accepting states are drawn with a double circle;
* parallel transitions between the same two states are merged into one
  arrow whose label lists the symbols separated by `` | ``.
"""

from __future__ import annotations

from collections import OrderedDict
from pathlib import Path

from resumelens.profiles import load_profiles
from resumelens.recognition import automaton_tuple, build_enfa, build_minimal_dfa


def _merged_edges(delta: list[tuple[str, str, str]]) -> "OrderedDict[tuple[str, str], list[str]]":
    edges: "OrderedDict[tuple[str, str], list[str]]" = OrderedDict()
    for source, symbol, target in delta:
        edges.setdefault((source, target), []).append(symbol)
    return edges


def to_mermaid(spec: dict, title: str = "") -> str:
    """Mermaid ``flowchart`` of a 5-tuple (renders directly on GitHub)."""
    lines = ["flowchart LR"]
    if title:
        lines.insert(0, f"%% {title}")
    lines.append("    start(( )) --> " + spec["q0"])
    for state in spec["Q"]:
        shape = f"((({state})))" if state in spec["F"] else f"(({state}))"
        lines.append(f"    {state}{shape}")
    for (source, target), symbols in _merged_edges(spec["delta"]).items():
        label = " | ".join(symbols)
        lines.append(f'    {source} -- "{label}" --> {target}')
    lines.append("    style start fill:none,stroke:none")
    return "\n".join(lines) + "\n"


def to_dot(spec: dict, title: str = "") -> str:
    """Graphviz DOT source of a 5-tuple (``dot -Tsvg file.dot``)."""
    lines = [
        "digraph automaton {",
        "    rankdir=LR;",
        '    node [shape=circle, fontname="Helvetica"];',
        '    edge [fontname="Helvetica", fontsize=10];',
    ]
    if title:
        lines.append(f'    labelloc="t"; label="{title}";')
    lines.append('    start [shape=point, width=0.15, label=""];')
    for state in spec["Q"]:
        shape = "doublecircle" if state in spec["F"] else "circle"
        lines.append(f'    "{state}" [shape={shape}];')
    lines.append(f'    start -> "{spec["q0"]}";')
    for (source, target), symbols in _merged_edges(spec["delta"]).items():
        label = "\\n".join(symbols)
        lines.append(f'    "{source}" -> "{target}" [label="{label}"];')
    lines.append("}")
    return "\n".join(lines) + "\n"


def tuple_markdown(spec: dict) -> str:
    """The 5-tuple written as Markdown (used by the diagrams index)."""
    delta_rows = "\n".join(f"| {p} | `{a}` | {q} |" for p, a, q in spec["delta"])
    return (
        f"* **Type:** {spec['kind']}\n"
        f"* **Q** = {{{', '.join(spec['Q'])}}}\n"
        f"* **Σ** = {{{', '.join(spec['Sigma'])}}}\n"
        f"* **q0** = {spec['q0']}\n"
        f"* **F** = {{{', '.join(spec['F'])}}}\n\n"
        "| State | Symbol | Next state |\n|---|---|---|\n"
        f"{delta_rows}\n"
    )


def export_all(out_dir: str | Path, profiles: list[dict] | None = None) -> list[Path]:
    """Write ``<profile>_enfa`` / ``<profile>_dfa`` diagrams (.mmd and .dot) and
    an index ``automata.md`` with the Mermaid diagrams and 5-tuples.

    Returns the list of written files.
    """
    folder = Path(out_dir)
    folder.mkdir(parents=True, exist_ok=True)
    selected = load_profiles() if profiles is None else profiles
    written: list[Path] = []
    index = [
        "# Stage 3 automata — transition diagrams",
        "",
        "Generated by `scripts/export_diagrams.py` from the automata in "
        "`src/resumelens/recognition.py`. Do not edit by hand.",
        "",
        "For every profile two equivalent automata are shown: the ε-NFA built "
        "directly from the profile slots, and the minimal DFA obtained by "
        "subset construction and minimization. Double circles are accepting states.",
        "",
    ]
    for profile in selected:
        name = profile["id"].lower()
        index.append(f"## {profile.get('display_name', profile['id'])} (`{profile['id']}`)")
        index.append("")
        for suffix, automaton, label in (
            ("enfa", build_enfa(profile), "ε-NFA"),
            ("dfa", build_minimal_dfa(profile), "Minimal DFA"),
        ):
            spec = automaton_tuple(automaton, profile)
            title = f"{profile['id']} - {label}"
            for extension, text in (("mmd", to_mermaid(spec, title)), ("dot", to_dot(spec, title))):
                path = folder / f"{name}_{suffix}.{extension}"
                path.write_text(text, encoding="utf-8")
                written.append(path)
            index += [
                f"### {label}",
                "",
                "```mermaid",
                to_mermaid(spec).rstrip(),
                "```",
                "",
                tuple_markdown(spec),
            ]
    index_path = folder / "automata.md"
    index_path.write_text("\n".join(index), encoding="utf-8")
    written.append(index_path)
    return written


__all__ = ["export_all", "to_dot", "to_mermaid", "tuple_markdown"]
