"""Stage 3 - qualification pattern recognition with finite automata (contract, Section 6.4).

Every profile is a list of ordered slots (see profiles.py). A profile pattern
is satisfied when, for every mandatory slot, at least one of its tokens
appears, the slots appear in order, and an optional slot may be absent
(decision D7). Over the alphabet Σ of canonical tokens this is the regular
language

    L(profile) = S1^k1 S2^k2 ... Sn^kn

where Si = (t_i1 | t_i2 | ...) is the union of the tokens of slot i and
ki = "+" for a mandatory slot or "*" for an optional one.

Construction (one automaton per profile, generated by the same function):

* states q0..qn: "the automaton is about to read slot i" (qn = all slots done);
* states p0..p(n-1): "at least one token of slot i has been read";
* qi --t--> pi  and  pi --t--> pi   for every token t of slot i;
* pi --ε--> q(i+1)                  (leave the slot after one or more tokens);
* qi --ε--> q(i+1)                  only if slot i is optional (skip it);
* start state q0, accepting states F = {qn}.

Because of the ε-transitions the automaton is an ε-NFA. It is the direct
translation of the slot semantics; its DFA equivalent is obtained by subset
construction (``build_dfa``) and then minimized (``build_minimal_dfa``).
``automaton_tuple`` exports the 5-tuple of any of them for the documentation.

The automaton reads the sequence produced by Stage 2b (``sort_for_profile``),
so only the tokens of the profile reach it and they arrive in slot order.
"""

from __future__ import annotations

from collections.abc import Iterable

from typing import Any

from pyformlang.finite_automaton import (
    DeterministicFiniteAutomaton,
    Epsilon,
    EpsilonNFA,
    State,
    Symbol,
)

from resumelens.models import ProfileResult
from resumelens.profiles import load_profiles
from resumelens.sorting import sort_for_profile


def slot_state(index: int) -> State:
    """q_i: the automaton is about to read slot ``index``."""
    return State(f"q{index}")


def inside_state(index: int) -> State:
    """p_i: at least one token of slot ``index`` has been read."""
    return State(f"p{index}")


def build_enfa(profile: dict) -> EpsilonNFA:
    """Build the ε-NFA M = (Q, Σ, δ, q0, F) that recognizes the profile pattern."""
    enfa = EpsilonNFA()
    slots = profile["slots"]
    enfa.add_start_state(slot_state(0))
    enfa.add_final_state(slot_state(len(slots)))

    for index, slot in enumerate(slots):
        here, inside, following = slot_state(index), inside_state(index), slot_state(index + 1)
        for token in slot["any_of"]:
            symbol = Symbol(token)
            enfa.add_transition(here, symbol, inside)    # first token of the slot
            enfa.add_transition(inside, symbol, inside)  # more tokens of the same slot
        enfa.add_transition(inside, Epsilon(), following)  # slot satisfied
        if slot["optional"]:
            enfa.add_transition(here, Epsilon(), following)  # slot skipped
    return enfa


def build_automaton(profile: dict) -> EpsilonNFA:
    """The automaton used to classify résumés for ``profile``."""
    return build_enfa(profile)


# --- equivalent deterministic automata ----------------------------------------

def build_dfa(profile: dict) -> DeterministicFiniteAutomaton:
    """DFA equivalent to the profile ε-NFA (subset construction with ε-closures)."""
    return build_enfa(profile).to_deterministic()


def build_minimal_dfa(profile: dict) -> DeterministicFiniteAutomaton:
    """Minimal DFA of the profile language (partition refinement)."""
    return build_dfa(profile).minimize()


# --- formal definition M = (Q, Σ, δ, q0, F) -----------------------------------

EPSILON = "ε"


def automaton_kind(automaton: Any) -> str:
    """Classify an automaton by its transition relation.

    * ``"ε-NFA"`` if some transition reads ε;
    * ``"NFA"`` if some (state, symbol) pair has more than one target or there
      is more than one start state;
    * ``"DFA"`` otherwise (δ is a partial function Q × Σ → Q; missing
      transitions go to an implicit dead state).
    """
    transitions = automaton.to_dict()
    nondeterministic = len(automaton.start_states) > 1
    for targets_by_symbol in transitions.values():
        for symbol, targets in targets_by_symbol.items():
            if isinstance(symbol, Epsilon) or str(symbol) == "epsilon":
                return "ε-NFA"
            if isinstance(targets, (set, frozenset)) and len(targets) > 1:
                nondeterministic = True
    return "NFA" if nondeterministic else "DFA"


def _readable_names(automaton: Any, alphabet: list[str]) -> dict[str, str]:
    """Rename states in breadth-first order from the start state.

    ε-NFA states keep their q_i / p_i names. States created by the subset
    construction (e.g. ``p4;q5``) are renamed D0, D1, ... so the 5-tuple and
    the diagrams are readable.
    """
    transitions = automaton.to_dict()
    order: list[str] = []
    queue = [str(s) for s in automaton.start_states]
    symbol_rank = {token: i for i, token in enumerate(alphabet)}
    while queue:
        state = queue.pop(0)
        if state in order:
            continue
        order.append(state)
        by_symbol = {str(k): v for k, v in transitions.get(State(state), {}).items()}
        for symbol in sorted(by_symbol, key=lambda s: symbol_rank.get(s, -1)):
            targets = by_symbol[symbol]
            targets = targets if isinstance(targets, (set, frozenset)) else {targets}
            queue.extend(sorted(str(t) for t in targets))
    for state in sorted(str(s) for s in automaton.states):  # unreachable states, if any
        if state not in order:
            order.append(state)
    if automaton_kind(automaton) == "ε-NFA":
        return {name: name for name in order}
    return {name: f"D{i}" for i, name in enumerate(order)}


def automaton_tuple(automaton: Any, profile: dict) -> dict:
    """Formal definition of ``automaton`` as plain, sorted Python data.

    Returns ``{"kind", "Q", "Sigma", "delta", "q0", "F"}`` where ``delta`` is a
    list of ``(state, symbol, state)`` triples (ε written as ``"ε"``). Used by
    the documentation and the diagram generator, so the formal definition is
    always produced from the same automaton that classifies résumés.
    """
    alphabet = [token for slot in profile["slots"] for token in slot["any_of"]]
    names = _readable_names(automaton, alphabet)
    rank = {name: i for i, name in enumerate(names.values())}
    symbol_rank = {token: i for i, token in enumerate(alphabet)}
    symbol_rank[EPSILON] = len(alphabet)

    delta: list[tuple[str, str, str]] = []
    for source, by_symbol in automaton.to_dict().items():
        for symbol, targets in by_symbol.items():
            label = EPSILON if str(symbol) == "epsilon" else str(symbol)
            targets = targets if isinstance(targets, (set, frozenset)) else {targets}
            for target in targets:
                delta.append((names[str(source)], label, names[str(target)]))
    delta.sort(key=lambda t: (rank[t[0]], symbol_rank.get(t[1], -1), rank[t[2]]))

    return {
        "kind": automaton_kind(automaton),
        "Q": sorted({names[str(s)] for s in automaton.states}, key=rank.__getitem__),
        "Sigma": alphabet,
        "delta": delta,
        "q0": names[str(next(iter(automaton.start_states)))],
        "F": sorted({names[str(s)] for s in automaton.final_states}, key=rank.__getitem__),
    }


def recognize(sequence: Iterable[str], profile: dict, automaton: EpsilonNFA | None = None) -> bool:
    """Run the profile automaton on an already sorted and filtered sequence."""
    machine = build_automaton(profile) if automaton is None else automaton
    return bool(machine.accepts([Symbol(token) for token in sequence]))


def classify(tokens: Iterable[str], profiles: list[dict] | None = None) -> list[ProfileResult]:
    """Evaluate the normalized tokens against every profile.

    For each profile: ``sequence = sort_for_profile(tokens, profile)`` and
    ``accepted = automaton.accepts(sequence)``. One ``ProfileResult`` is
    returned per profile, in the same order as ``profiles`` (default: the
    four profiles of ``profiles/``). A résumé may be accepted by several
    profiles or by none; the result is not a ranking.
    """
    token_list = list(tokens)
    selected = load_profiles() if profiles is None else profiles
    results: list[ProfileResult] = []
    for profile in selected:
        sequence = sort_for_profile(token_list, profile)
        results.append(
            ProfileResult(
                profile_id=profile["id"],
                sequence=sequence,
                accepted=recognize(sequence, profile),
            )
        )
    return results


__all__ = [
    "EPSILON",
    "automaton_kind",
    "automaton_tuple",
    "build_automaton",
    "build_dfa",
    "build_enfa",
    "build_minimal_dfa",
    "classify",
    "inside_state",
    "recognize",
    "slot_state",
]
