"""Stage 3 - qualification pattern recognition with finite automata (contract, Section 6.4).

Every profile is a list of ordered slots (see profiles.py). A profile pattern
is satisfied when, for every mandatory slot, at least one of its tokens
appears, the slots appear in order, and an optional slot may be absent
(decision D7). Over the alphabet Σ of canonical tokens this is the regular
language

    L(profile) = S1^k1 S2^k2 ... Sn^kn

where Si = (t_i1 | t_i2 | ...) is the union of the tokens of slot i and
ki = "+" for a mandatory slot or "*" for an optional one.

Construction (one automaton per profile, generated by the same function):

* states q0..qn: "the automaton is about to read slot i" (qn = all slots done);
* states p0..p(n-1): "at least one token of slot i has been read";
* qi --t--> pi  and  pi --t--> pi   for every token t of slot i;
* pi --ε--> q(i+1)                  (leave the slot after one or more tokens);
* qi --ε--> q(i+1)                  only if slot i is optional (skip it);
* start state q0, accepting states F = {qn}.

Because of the ε-transitions the automaton is an ε-NFA. It is the direct
translation of the slot semantics; its DFA equivalent is obtained by subset
construction (pyformlang ``to_deterministic``).

The automaton reads the sequence produced by Stage 2b (``sort_for_profile``),
so only the tokens of the profile reach it and they arrive in slot order.
"""

from __future__ import annotations

from collections.abc import Iterable

from pyformlang.finite_automaton import Epsilon, EpsilonNFA, State, Symbol

from resumelens.models import ProfileResult
from resumelens.profiles import load_profiles
from resumelens.sorting import sort_for_profile


def slot_state(index: int) -> State:
    """q_i: the automaton is about to read slot ``index``."""
    return State(f"q{index}")


def inside_state(index: int) -> State:
    """p_i: at least one token of slot ``index`` has been read."""
    return State(f"p{index}")


def build_enfa(profile: dict) -> EpsilonNFA:
    """Build the ε-NFA M = (Q, Σ, δ, q0, F) that recognizes the profile pattern."""
    enfa = EpsilonNFA()
    slots = profile["slots"]
    enfa.add_start_state(slot_state(0))
    enfa.add_final_state(slot_state(len(slots)))

    for index, slot in enumerate(slots):
        here, inside, following = slot_state(index), inside_state(index), slot_state(index + 1)
        for token in slot["any_of"]:
            symbol = Symbol(token)
            enfa.add_transition(here, symbol, inside)    # first token of the slot
            enfa.add_transition(inside, symbol, inside)  # more tokens of the same slot
        enfa.add_transition(inside, Epsilon(), following)  # slot satisfied
        if slot["optional"]:
            enfa.add_transition(here, Epsilon(), following)  # slot skipped
    return enfa


def build_automaton(profile: dict) -> EpsilonNFA:
    """The automaton used to classify résumés for ``profile``."""
    return build_enfa(profile)


def recognize(sequence: Iterable[str], profile: dict, automaton: EpsilonNFA | None = None) -> bool:
    """Run the profile automaton on an already sorted and filtered sequence."""
    machine = build_automaton(profile) if automaton is None else automaton
    return bool(machine.accepts([Symbol(token) for token in sequence]))


def classify(tokens: Iterable[str], profiles: list[dict] | None = None) -> list[ProfileResult]:
    """Evaluate the normalized tokens against every profile.

    For each profile: ``sequence = sort_for_profile(tokens, profile)`` and
    ``accepted = automaton.accepts(sequence)``. One ``ProfileResult`` is
    returned per profile, in the same order as ``profiles`` (default: the
    four profiles of ``profiles/``). A résumé may be accepted by several
    profiles or by none; the result is not a ranking.
    """
    token_list = list(tokens)
    selected = load_profiles() if profiles is None else profiles
    results: list[ProfileResult] = []
    for profile in selected:
        sequence = sort_for_profile(token_list, profile)
        results.append(
            ProfileResult(
                profile_id=profile["id"],
                sequence=sequence,
                accepted=recognize(sequence, profile),
            )
        )
    return results


__all__ = [
    "build_automaton",
    "build_enfa",
    "classify",
    "inside_state",
    "recognize",
    "slot_state",
]
